exports_files([
    "bubble_sort.lisp",
    "factorial.lisp",
    "fibonacci.lisp",
    "io_demo.lisp",
    "list_reversal.lisp",
])

filegroup(
    name = "lisp_examples",
    srcs = glob(["*.lisp"]),
    visibility = ["//visibility:public"],
)